version: '3'

tasks:
  install:
    desc: Install all dependencies using Poetry
    cmds:
      - /Users/valeriiastartseva/.local/bin/poetry install

  runserver:
    desc: Start local server
    cmds:
      - /Users/valeriiastartseva/.local/bin/poetry run python manage.py runserver

  migrate:
    desc: Migrate DB
    cmds:
      - /Users/valeriiastartseva/.local/bin/poetry run python manage.py migrate

  makemigrations:
    desc: Create migrations for model
    cmds:
      - /Users/valeriiastartseva/.local/bin/poetry run python manage.py makemigrations

  createsuperuser:
    desc: Create superuser
    cmds:
      - /Users/valeriiastartseva/.local/bin/poetry run python manage.py createsuperuser

  shell:
    desc: Start django shell console
    cmds:
      - /Users/valeriiastartseva/.local/bin/poetry run python manage.py shell
