version: '3'

tasks:
  install:
    desc: Install all dependencies using Poetry
    cmds:
      - /Users/valeriiastartseva/.local/bin/poetry install

  collectstatic:
    desc: collect statics
    cmds:
      - /Users/valeriiastartseva/.local/bin/poetry run python manage.py collectstatic

  runserver:
    desc: Start local server
    cmds:
      - /Users/valeriiastartseva/.local/bin/poetry run python manage.py runserver

  migrate:
    desc: Migrate DB
    cmds:
      - /Users/valeriiastartseva/.local/bin/poetry run python manage.py migrate

  makemigrations:
    desc: Create migrations for model
    cmds:
      - /Users/valeriiastartseva/.local/bin/poetry run python manage.py makemigrations

  createsuperuser:
    desc: Create superuser
    cmds:
      - /Users/valeriiastartseva/.local/bin/poetry run python manage.py createsuperuser

  shell:
    desc: Start django shell console
    cmds:
      - /Users/valeriiastartseva/.local/bin/poetry run python manage.py shell

  git_push:
    desc: Commit and push changes to the repository with a custom commit message
    cmds:
      - git add .
      - |
        echo "Enter your commit message:"
        read commit_message
        git commit -m "$commit_message"
      - git push origin main
