# Generated by Django 5.1.2 on 2024-11-03 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('houses', '0002_initial'),
        ('payments_section', '0001_initial'),
        ('service', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exstatement',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='instatement',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments_section.account'),
        ),
        migrations.AddField(
            model_name='instatement',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='instatement',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_instatements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='personalaccount',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.apartment'),
        ),
        migrations.AddField(
            model_name='personalaccount',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.house'),
        ),
        migrations.AddField(
            model_name='personalaccount',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.section'),
        ),
        migrations.AddField(
            model_name='instatement',
            name='personal_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments_section.personalaccount'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.apartment'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.house'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receipt',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.section'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service'),
        ),
    ]
