# Generated by Django 5.1.2 on 2024-12-10 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments_section', '0003_alter_personalaccount_apartment_and_more'),
        ('service', '0004_account_alter_tariff_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instatement',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.account'),
        ),
        migrations.AlterField(
            model_name='exstatement',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.account'),
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
