# Generated by Django 5.1.2 on 2024-12-03 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_service_unit_of_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='unit_of_change',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.unitofchange'),
        ),
    ]
