# Generated by Django 5.1.2 on 2024-12-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_account_alter_tariff_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('income', 'Прихід'), ('expenses', 'Розхід')], default='income', max_length=15),
        ),
    ]
