# Generated by Django 5.1.2 on 2024-11-05 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('view_dashboard', 'Can view dashboard'), ('view_payment_section', 'Can view payment section'), ('view_personal_account', 'Can view personal account'), ('view_apartments', 'Can view apartments'), ('view_apartments_owners', 'Can view apartments owners'), ('view_houses', 'Can view houses'), ('view_messages', 'Can view messages'), ('view_master_application', 'Can view master application'), ('view_services_house', 'Can view services house'), ('view_manage_site', 'Can manage site'), ('view_system_settings', 'Can view system settings'), ('view_services', 'Can view services'), ('view_tariffs', 'Can view tariffs'), ('view_roles', 'Can view roles'), ('view_users', 'Can view users'), ('view_payment_details', 'Can view payment details'), ('payment_section', 'Can access payment section'), ('master_application', 'Can access master application'), ('services_house', 'Can access services house')]},
        ),
    ]
