# Generated by Django 5.1.2 on 2024-11-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='house',
        ),
        migrations.RemoveField(
            model_name='house',
            name='gallery',
        ),
        migrations.AddField(
            model_name='apartment',
            name='apartment_area',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='house',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='house',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='house',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='house',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='house',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
