# Generated by Django 5.1.2 on 2024-11-16 16:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_remove_apartment_house_remove_house_gallery_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='staff',
        ),
        migrations.AddField(
            model_name='house',
            name='staff',
            field=models.ManyToManyField(blank=True, related_name='houses', to=settings.AUTH_USER_MODEL),
        ),
    ]
