# Generated by Django 5.1.2 on 2024-11-22 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0006_staff_house_staff_user_delete_houseuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floor',
            name='section',
        ),
    ]
